apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: srcpythonhelloworld-path-to-kubernetes-oqog
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srcpythonhelloworld-path-to-kubernetes-oqog
    app.kubernetes.io/part-of: my-app-7
  name: srcpythonhelloworld-path-to-kubernetes-oqog
  namespace: jkopriva-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: srcpythonhelloworld-path-to-kubernetes-oqog
status:
  loadBalancer: {}
